server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rentacargy
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true # SQL sorgularını konsola yazdırmak için
        format_sql: true # Yazılan SQL sorgularını düzenlemek için